# Generated by Django 2.0.7 on 2018-09-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comback_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='linked_to',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
